language: rust

notifications:
  webhooks: http://build.servo.org:54856/travis

matrix:
  include:
    - rust: stable
      env: FEATURES=""
    - rust: stable
      env: FEATURES="mint"
    - rust: beta
      env: FEATURES=""
    - rust: nightly
      env: FEATURES=""
    - rust: nightly
      env: FEATURES="unstable"

script:
  - cargo build --verbose --features "$FEATURES"
  - cargo test --verbose --features "$FEATURES"
